// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "ruby.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// RUBY_DATA_FUNC_e7ca08a is a proxy for callback RUBY_DATA_FUNC.
void RUBY_DATA_FUNC_e7ca08a(void* arg0);

// rb_event_hook_func_t_7bd0f07c is a proxy for callback rb_event_hook_func_t.
void rb_event_hook_func_t_7bd0f07c(unsigned int evflag, unsigned long int data, unsigned long int self, unsigned long int mid, unsigned long int klass);

// ruby_glob_func_2a0d65ed is a proxy for callback ruby_glob_func.
int ruby_glob_func_2a0d65ed(char* path, unsigned long int arg, void* enc);

// rb_enumerator_size_func_4cdc9e33 is a proxy for callback rb_enumerator_size_func.
unsigned long int rb_enumerator_size_func_4cdc9e33(unsigned long int recv, unsigned long int argv, unsigned long int eobj);

// rb_hash_update_func_786399f4 is a proxy for callback rb_hash_update_func.
unsigned long int rb_hash_update_func_786399f4(unsigned long int newkey, unsigned long int oldkey, unsigned long int value);

// rb_unblock_function_t_5eb9b247 is a proxy for callback rb_unblock_function_t.
void rb_unblock_function_t_5eb9b247(void* arg0);

// rb_blocking_function_t_a90bb1d3 is a proxy for callback rb_blocking_function_t.
unsigned long int rb_blocking_function_t_a90bb1d3(void* arg0);

// rb_alloc_func_t_43df300 is a proxy for callback rb_alloc_func_t.
unsigned long int rb_alloc_func_t_43df300(unsigned long int klass);

// rb_block_call_func_d886170c is a proxy for callback rb_block_call_func.
unsigned long int rb_block_call_func_d886170c(unsigned long int yielded_arg, unsigned long int callback_arg, int argc, unsigned long int* argv, unsigned long int blockarg);

// rb_block_call_func_t_4f4f40c is a proxy for callback rb_block_call_func_t.
unsigned long int rb_block_call_func_t_4f4f40c(unsigned long int yielded_arg, unsigned long int callback_arg, int argc, unsigned long int* argv, unsigned long int blockarg);

// rb_gvar_getter_t_f727b057 is a proxy for callback rb_gvar_getter_t.
unsigned long int rb_gvar_getter_t_f727b057(unsigned long int id, unsigned long int* data);

// rb_gvar_setter_t_fd68f86 is a proxy for callback rb_gvar_setter_t.
void rb_gvar_setter_t_fd68f86(unsigned long int val, unsigned long int id, unsigned long int* data);

// rb_gvar_marker_t_a6416bc2 is a proxy for callback rb_gvar_marker_t.
void rb_gvar_marker_t_a6416bc2(unsigned long int* _var);

