// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated 
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void RUBY_DATA_FUNC_e7ca08a(void* arg0) {
	rUBYDATAFUNCE7CA08A(arg0);
}

void rb_event_hook_func_t_7bd0f07c(unsigned int evflag, unsigned long int data, unsigned long int self, unsigned long int mid, unsigned long int klass) {
	rbEventHookFuncT7BD0F07C(evflag, data, self, mid, klass);
}

int ruby_glob_func_2a0d65ed(char* path, unsigned long int arg, void* enc) {
	return rubyGlobFunc2A0D65ED(path, arg, enc);
}

unsigned long int rb_enumerator_size_func_4cdc9e33(unsigned long int recv, unsigned long int argv, unsigned long int eobj) {
	return rbEnumeratorSizeFunc4CDC9E33(recv, argv, eobj);
}

unsigned long int rb_hash_update_func_786399f4(unsigned long int newkey, unsigned long int oldkey, unsigned long int value) {
	return rbHashUpdateFunc786399F4(newkey, oldkey, value);
}

void rb_unblock_function_t_5eb9b247(void* arg0) {
	rbUnblockFunctionT5EB9B247(arg0);
}

unsigned long int rb_blocking_function_t_a90bb1d3(void* arg0) {
	return rbBlockingFunctionTA90BB1D3(arg0);
}

unsigned long int rb_alloc_func_t_43df300(unsigned long int klass) {
	return rbAllocFuncT43DF300(klass);
}

unsigned long int rb_block_call_func_d886170c(unsigned long int yielded_arg, unsigned long int callback_arg, int argc, unsigned long int* argv, unsigned long int blockarg) {
	return rbBlockCallFuncD886170C(yielded_arg, callback_arg, argc, argv, blockarg);
}

unsigned long int rb_block_call_func_t_4f4f40c(unsigned long int yielded_arg, unsigned long int callback_arg, int argc, unsigned long int* argv, unsigned long int blockarg) {
	return rbBlockCallFuncT4F4F40C(yielded_arg, callback_arg, argc, argv, blockarg);
}

unsigned long int rb_gvar_getter_t_f727b057(unsigned long int id, unsigned long int* data) {
	return rbGvarGetterTF727B057(id, data);
}

void rb_gvar_setter_t_fd68f86(unsigned long int val, unsigned long int id, unsigned long int* data) {
	rbGvarSetterTFD68F86(val, id, data);
}

void rb_gvar_marker_t_a6416bc2(unsigned long int* _var) {
	rbGvarMarkerTA6416BC2(_var);
}

