package ruby

import "C"

import (
	"unsafe"
)

// FIXME: Following cannot be successfully auto-generated by c-for-go...

func (v VALUE) PassRef() (*C.VALUE, *cgoAllocMap) {
	ref := (*C.VALUE)(unsafe.Pointer(&v))
	return ref, cgoAllocsUnknown
}
