package ruby

/*
#include "ruby.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

import (
	"unsafe"
)

// FIXME: Following cannot be successfully auto-generated by c-for-go...

func (v VALUE) PassRef() (*[0]byte, *cgoAllocMap) { //nolint:revive
	ref := (*[0]byte)(unsafe.Pointer(&v))
	return ref, cgoAllocsUnknown
}
