// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const ()

// RbWarningCategoryT as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
type RbWarningCategoryT int32

// RbWarningCategoryT enumeration from https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
const (
	RbWarnCategoryNone         RbWarningCategoryT = C.RB_WARN_CATEGORY_NONE
	RbWarnCategoryDeprecated   RbWarningCategoryT = C.RB_WARN_CATEGORY_DEPRECATED
	RbWarnCategoryExperimental RbWarningCategoryT = C.RB_WARN_CATEGORY_EXPERIMENTAL
	RbWarnCategoryPerformance  RbWarningCategoryT = C.RB_WARN_CATEGORY_PERFORMANCE
	RbWarnCategoryDefaultBits  RbWarningCategoryT = C.RB_WARN_CATEGORY_DEFAULT_BITS
	RbWarnCategoryAllBits      RbWarningCategoryT = C.RB_WARN_CATEGORY_ALL_BITS
)

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const (
	// RbIoWaitReadable as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
	RbIoWaitReadable = C.RB_IO_WAIT_READABLE
	// RbIoWaitWritable as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
	RbIoWaitWritable = C.RB_IO_WAIT_WRITABLE
)

const ()

const ()

const ()

const ()

const ()

const ()
