// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Qfalse as defined in https://github.com/ruby/ruby/blob/master/include/ruby/internal/special_consts.h
	Qfalse = 0x100e637b0
	// Qnil as defined in https://github.com/ruby/ruby/blob/master/include/ruby/internal/special_consts.h
	Qnil = 0x100e637b0
	// Qtrue as defined in https://github.com/ruby/ruby/blob/master/include/ruby/internal/special_consts.h
	Qtrue = 0x100e637b0
	// Qundef as defined in https://github.com/ruby/ruby/blob/master/include/ruby/internal/special_consts.h
	Qundef = 0x100e637b0
)

// RbWarningCategoryT as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
type RbWarningCategoryT int32

// RbWarningCategoryT enumeration from https://github.com/ruby/ruby/blob/master/include/ruby/internal/error.h
const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
