// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RubyValueType is a type for passing `C.ruby_value_type` in and out of package
type RubyValueType int

// RubyValueType enumeration
const (
	RUBY_T_ARRAY    RubyValueType = C.RUBY_T_ARRAY
	RUBY_T_BIGNUM   RubyValueType = C.RUBY_T_BIGNUM
	RUBY_T_CLASS    RubyValueType = C.RUBY_T_CLASS
	RUBY_T_COMPLEX  RubyValueType = C.RUBY_T_COMPLEX
	RUBY_T_DATA     RubyValueType = C.RUBY_T_DATA
	RUBY_T_FALSE    RubyValueType = C.RUBY_T_FALSE
	RUBY_T_FILE     RubyValueType = C.RUBY_T_FILE
	RUBY_T_FIXNUM   RubyValueType = C.RUBY_T_FIXNUM
	RUBY_T_FLOAT    RubyValueType = C.RUBY_T_FLOAT
	RUBY_T_HASH     RubyValueType = C.RUBY_T_HASH
	RUBY_T_ICLASS   RubyValueType = C.RUBY_T_ICLASS
	RUBY_T_IMEMO    RubyValueType = C.RUBY_T_IMEMO
	RUBY_T_MASK     RubyValueType = C.RUBY_T_MASK
	RUBY_T_MATCH    RubyValueType = C.RUBY_T_MATCH
	RUBY_T_MODULE   RubyValueType = C.RUBY_T_MODULE
	RUBY_T_MOVED    RubyValueType = C.RUBY_T_MOVED
	RUBY_T_NIL      RubyValueType = C.RUBY_T_NIL
	RUBY_T_NODE     RubyValueType = C.RUBY_T_NODE
	RUBY_T_NONE     RubyValueType = C.RUBY_T_NONE
	RUBY_T_OBJECT   RubyValueType = C.RUBY_T_OBJECT
	RUBY_T_RATIONAL RubyValueType = C.RUBY_T_RATIONAL
	RUBY_T_REGEXP   RubyValueType = C.RUBY_T_REGEXP
	RUBY_T_STRING   RubyValueType = C.RUBY_T_STRING
	RUBY_T_STRUCT   RubyValueType = C.RUBY_T_STRUCT
	RUBY_T_SYMBOL   RubyValueType = C.RUBY_T_SYMBOL
	RUBY_T_TRUE     RubyValueType = C.RUBY_T_TRUE
	RUBY_T_UNDEF    RubyValueType = C.RUBY_T_UNDEF
	RUBY_T_ZOMBIE   RubyValueType = C.RUBY_T_ZOMBIE
)
