// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbStructAref calls `rb_struct_aref` in C
//
// Original definition is following
//
//	VALUE rb_struct_aref(VALUE st, VALUE k)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstruct.h
func RbStructAref(st VALUE, k VALUE) VALUE {
	ret := VALUE(C.rb_struct_aref(C.VALUE(st), C.VALUE(k)))
	return ret
}

// RbStructAset calls `rb_struct_aset` in C
//
// Original definition is following
//
//	VALUE rb_struct_aset(VALUE st, VALUE k, VALUE v)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstruct.h
func RbStructAset(st VALUE, k VALUE, v VALUE) VALUE {
	ret := VALUE(C.rb_struct_aset(C.VALUE(st), C.VALUE(k), C.VALUE(v)))
	return ret
}
