// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbHashSetIfnone calls `rb_hash_set_ifnone` in C
//
// Original definition is following
//
//	VALUE rb_hash_set_ifnone(VALUE hash, VALUE ifnone)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rhash.h
func RbHashSetIfnone(hash VALUE, ifnone VALUE) VALUE {
	ret := VALUE(C.rb_hash_set_ifnone(C.VALUE(hash), C.VALUE(ifnone)))
	return ret
}

// RbHashTbl calls `rb_hash_tbl` in C
//
// Original definition is following
//
//	struct st_table *rb_hash_tbl(VALUE hash, const char *file, int line)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rhash.h
func RbHashTbl(hash VALUE, file string, line int) *StTable {
	char, clean := string2Char(file)
	defer clean()

	ret := (*StTable)(C.rb_hash_tbl(C.VALUE(hash), char, C.int(line)))
	return ret
}
