// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbDebugRstringNullPtr calls `rb_debug_rstring_null_ptr` in C
//
// Original definition is following
//
//	void rb_debug_rstring_null_ptr(const char *func)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbDebugRstringNullPtr(fun string) {
	char, clean := string2Char(fun)
	defer clean()

	C.rb_debug_rstring_null_ptr(char)
}

// RbStrExport calls `rb_str_export` in C
//
// Original definition is following
//
//	VALUE rb_str_export(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbStrExport(obj VALUE) VALUE {
	ret := VALUE(C.rb_str_export(C.VALUE(obj)))
	return ret
}

// RbStrExportLocale calls `rb_str_export_locale` in C
//
// Original definition is following
//
//	VALUE rb_str_export_locale(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbStrExportLocale(obj VALUE) VALUE {
	ret := VALUE(C.rb_str_export_locale(C.VALUE(obj)))
	return ret
}

// RbStringValue calls `rb_string_value` in C
//
// Original definition is following
//
//	VALUE rb_string_value(volatile VALUE *ptr)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbStringValue(ptr *VALUE) VALUE {
	var cPtr C.VALUE
	ret := VALUE(C.rb_string_value(&cPtr))
	*ptr = VALUE(cPtr)
	return ret
}

// RbStringValueCstr calls `rb_string_value_cstr` in C
//
// Original definition is following
//
//	char *rb_string_value_cstr(volatile VALUE *ptr)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbStringValueCstr(ptr *VALUE) string {
	var cPtr C.VALUE
	ret := string(C.rb_string_value_cstr(&cPtr))
	*ptr = VALUE(cPtr)
	return ret
}

// RbStringValuePtr calls `rb_string_value_ptr` in C
//
// Original definition is following
//
//	char *rb_string_value_ptr(volatile VALUE *ptr)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rstring.h
func RbStringValuePtr(ptr *VALUE) string {
	var cPtr C.VALUE
	ret := string(C.rb_string_value_ptr(&cPtr))
	*ptr = VALUE(cPtr)
	return ret
}
