// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbEncVsprintf calls `rb_enc_vsprintf` in C
//
// Original definition is following
//
//	VALUE rb_enc_vsprintf(rb_encoding *enc, const char *fmt, va_list ap)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/encoding/sprintf.h
func RbEncVsprintf(enc *RbEncoding, fmt string, ap VaList) VALUE {
	char, clean := string2Char(fmt)
	defer clean()

	var cEnc C.rb_encoding
	ret := VALUE(C.rb_enc_vsprintf(&cEnc, char, C.va_list(ap)))
	*enc = RbEncoding(cEnc)
	return ret
}
