// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbBackrefGet calls `rb_backref_get` in C
//
// Original definition is following
//
//	VALUE rb_backref_get(void)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbBackrefGet() VALUE {
	ret := VALUE(C.rb_backref_get())
	return ret
}

// RbBackrefSet calls `rb_backref_set` in C
//
// Original definition is following
//
//	void rb_backref_set(VALUE md)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbBackrefSet(md VALUE) {
	C.rb_backref_set(C.VALUE(md))
}

// RbLastlineGet calls `rb_lastline_get` in C
//
// Original definition is following
//
//	VALUE rb_lastline_get(void)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbLastlineGet() VALUE {
	ret := VALUE(C.rb_lastline_get())
	return ret
}

// RbLastlineSet calls `rb_lastline_set` in C
//
// Original definition is following
//
//	void rb_lastline_set(VALUE str)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbLastlineSet(str VALUE) {
	C.rb_lastline_set(C.VALUE(str))
}

// RbSymAllSymbols calls `rb_sym_all_symbols` in C
//
// Original definition is following
//
//	VALUE rb_sym_all_symbols(void)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbSymAllSymbols() VALUE {
	ret := VALUE(C.rb_sym_all_symbols())
	return ret
}

// RbSymnameP calls `rb_symname_p` in C
//
// Original definition is following
//
//	int rb_symname_p(const char *str)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/parse.h
func RbSymnameP(str string) int {
	char, clean := string2Char(str)
	defer clean()

	ret := int(C.rb_symname_p(char))
	return ret
}
