// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbAryPtrUseEnd calls `rb_ary_ptr_use_end` in C
//
// Original definition is following
//
//	void rb_ary_ptr_use_end(VALUE a)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rarray.h
func RbAryPtrUseEnd(a VALUE) {
	C.rb_ary_ptr_use_end(C.VALUE(a))
}
