// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbAtomicT is a type for passing `C.rb_atomic_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/atomic.h
type RbAtomicT C.rb_atomic_t
