// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbThreadFdSelect calls `rb_thread_fd_select` in C
//
// Original definition is following
//
//	int rb_thread_fd_select(int nfds, rb_fdset_t *rfds, rb_fdset_t *wfds, rb_fdset_t *efds, struct timeval *timeout)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/select.h
func RbThreadFdSelect(nfds int, rfds *RbFdsetT, wfds *RbFdsetT, efds *RbFdsetT, timeout *Timeval) int {
	var cRfds C.rb_fdset_t
	var cWfds C.rb_fdset_t
	var cEfds C.rb_fdset_t
	var cTimeout C.struct_timeval
	ret := int(C.rb_thread_fd_select(C.int(nfds), &cRfds, &cWfds, &cEfds, &cTimeout))
	*rfds = RbFdsetT(cRfds)
	*wfds = RbFdsetT(cWfds)
	*efds = RbFdsetT(cEfds)
	*timeout = Timeval(cTimeout)
	return ret
}
