// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbEventFlagT is a type for passing `C.rb_event_flag_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/event.h
type RbEventFlagT C.rb_event_flag_t

// RbEventHookFuncT is a type for passing `C.rb_event_hook_func_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/event.h
type RbEventHookFuncT C.rb_event_hook_func_t

// RbRemoveEventHook calls `rb_remove_event_hook` in C
//
// Original definition is following
//
//	int rb_remove_event_hook(rb_event_hook_func_t func)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/event.h
func RbRemoveEventHook(fun RbEventHookFuncT) int {
	ret := int(C.rb_remove_event_hook(C.rb_event_hook_func_t(fun)))
	return ret
}
