// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

import (
	"unsafe"
)

// RbRandomDataTypeT is a type for passing `C.rb_random_data_type_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomDataTypeT C.rb_random_data_type_t

// RbRandomGetBytesFunc is a type for passing `C.rb_random_get_bytes_func` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomGetBytesFunc C.rb_random_get_bytes_func

// RbRandomGetInt32Func is a type for passing `C.rb_random_get_int32_func` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomGetInt32Func C.rb_random_get_int32_func

// RbRandomGetRealFunc is a type for passing `C.rb_random_get_real_func` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomGetRealFunc C.rb_random_get_real_func

// RbRandomInitFunc is a type for passing `C.rb_random_init_func` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomInitFunc C.rb_random_init_func

// RbRandomInitInt32Func is a type for passing `C.rb_random_init_int32_func` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomInitInt32Func C.rb_random_init_int32_func

// RbRandomInterfaceT is a type for passing `C.rb_random_interface_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomInterfaceT C.rb_random_interface_t

// RbRandomT is a type for passing `C.rb_random_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomT C.rb_random_t

// RbRandomStruct is a type for passing `C.rb_random_struct` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
type RbRandomStruct C.rb_random_struct

// RbIntPairToReal calls `rb_int_pair_to_real` in C
//
// Original definition is following
//
//	double rb_int_pair_to_real(uint32_t a, uint32_t b, int excl)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
func RbIntPairToReal(a Uint32T, b Uint32T, excl int) Double {
	ret := Double(C.rb_int_pair_to_real(C.uint32_t(a), C.uint32_t(b), C.int(excl)))
	return ret
}

// RbRandBytesInt32 calls `rb_rand_bytes_int32` in C
//
// Original definition is following
//
//	void rb_rand_bytes_int32(rb_random_get_int32_func *func, rb_random_t *prng, void *buff, size_t size)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
func RbRandBytesInt32(fun *RbRandomGetInt32Func, prng *RbRandomT, buff unsafe.Pointer, size SizeT) {
	var cFun C.rb_random_get_int32_func
	var cPrng C.rb_random_t
	C.rb_rand_bytes_int32(&cFun, &cPrng, toCPointer(buff), C.size_t(size))
	*fun = RbRandomGetInt32Func(cFun)
	*prng = RbRandomT(cPrng)
}

// RbRandomBaseInit calls `rb_random_base_init` in C
//
// Original definition is following
//
//	void rb_random_base_init(rb_random_t *rnd)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
func RbRandomBaseInit(rnd *RbRandomT) {
	var cRnd C.rb_random_t
	C.rb_random_base_init(&cRnd)
	*rnd = RbRandomT(cRnd)
}

// RbRandomMark calls `rb_random_mark` in C
//
// Original definition is following
//
//	void rb_random_mark(void *ptr)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/random.h
func RbRandomMark(ptr unsafe.Pointer) {
	C.rb_random_mark(toCPointer(ptr))
}
