// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbObjReveal calls `rb_obj_reveal` in C
//
// Original definition is following
//
//	VALUE rb_obj_reveal(VALUE obj, VALUE klass); /* do not use this API to change klass information */RBIMPL_SYMBOL_EXPORT_END()RBIMPL_ATTR_PURE_UNLESS_DEBUG()RBIMPL_ATTR_ARTIFICIAL()/*** Queries the class of an object.** @param[in]  obj  An object.* @return     Its class.*/static inline VALUERBASIC_CLASS(VALUE obj){RBIMPL_ASSERT_OR_ASSUME(! RB_SPECIAL_CONST_P(obj))
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rbasic.h
func RbObjReveal(obj VALUE, klass VALUE) VALUE {
	ret := VALUE(C.rb_obj_reveal(C.VALUE(obj), C.VALUE(klass)))
	return ret
}
