// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbRational calls `rb_Rational` in C
//
// Original definition is following
//
//	VALUE rb_Rational(VALUE num, VALUE den)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/rational.h
func RbRational(num VALUE, den VALUE) VALUE {
	ret := VALUE(C.rb_Rational(C.VALUE(num), C.VALUE(den)))
	return ret
}

// RbFltRationalize calls `rb_flt_rationalize` in C
//
// Original definition is following
//
//	VALUE rb_flt_rationalize(VALUE flt)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/rational.h
func RbFltRationalize(flt VALUE) VALUE {
	ret := VALUE(C.rb_flt_rationalize(C.VALUE(flt)))
	return ret
}

// RbFltRationalizeWithPrec calls `rb_flt_rationalize_with_prec` in C
//
// Original definition is following
//
//	VALUE rb_flt_rationalize_with_prec(VALUE flt, VALUE prec)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/rational.h
func RbFltRationalizeWithPrec(flt VALUE, prec VALUE) VALUE {
	ret := VALUE(C.rb_flt_rationalize_with_prec(C.VALUE(flt), C.VALUE(prec)))
	return ret
}

// RbRationalNew calls `rb_rational_new` in C
//
// Original definition is following
//
//	VALUE rb_rational_new(VALUE num, VALUE den)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/rational.h
func RbRationalNew(num VALUE, den VALUE) VALUE {
	ret := VALUE(C.rb_rational_new(C.VALUE(num), C.VALUE(den)))
	return ret
}
