// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbCheckCopyable calls `rb_check_copyable` in C
//
// Original definition is following
//
//	void rb_check_copyable(VALUE obj, VALUE orig)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbCheckCopyable(obj VALUE, orig VALUE) {
	C.rb_check_copyable(C.VALUE(obj), C.VALUE(orig))
}

// RbCheckFrozen calls `rb_check_frozen` in C
//
// Original definition is following
//
//	void rb_check_frozen(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbCheckFrozen(obj VALUE) {
	C.rb_check_frozen(C.VALUE(obj))
}

// RbErrorFrozen calls `rb_error_frozen` in C
//
// Original definition is following
//
//	void rb_error_frozen(const char *what)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbErrorFrozen(what string) {
	char, clean := string2Char(what)
	defer clean()

	C.rb_error_frozen(char)
}

// RbExcNewCstr calls `rb_exc_new_cstr` in C
//
// Original definition is following
//
//	VALUE rb_exc_new_cstr(VALUE etype, const char *str)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbExcNewCstr(etype VALUE, str string) VALUE {
	char, clean := string2Char(str)
	defer clean()

	ret := VALUE(C.rb_exc_new_cstr(C.VALUE(etype), char))
	return ret
}

// RbExcNewStr calls `rb_exc_new_str` in C
//
// Original definition is following
//
//	VALUE rb_exc_new_str(VALUE etype, VALUE str)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbExcNewStr(etype VALUE, str VALUE) VALUE {
	ret := VALUE(C.rb_exc_new_str(C.VALUE(etype), C.VALUE(str)))
	return ret
}

// RbInvalidStr calls `rb_invalid_str` in C
//
// Original definition is following
//
//	void rb_invalid_str(const char *str, const char *type)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbInvalidStr(str string, r string) {
	charStr, cleanCharstr := string2Char(str)
	defer cleanCharstr()

	charR, cleanCharr := string2Char(r)
	defer cleanCharr()

	C.rb_invalid_str(charStr, charR)
}

// RbCheckArity calls `rb_check_arity` in C
//
// Original definition is following
//
//	rb_check_arity(int argc, int min, int max)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/error.h
func RbCheckArity(argc int, min int, max int) int {
	ret := int(C.rb_check_arity(C.int(argc), C.int(min), C.int(max)))
	return ret
}
