// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

import (
	"unsafe"
)

// RbGetArgv calls `rb_get_argv` in C
//
// Original definition is following
//
//	VALUE rb_get_argv(void)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/ruby.h
func RbGetArgv() VALUE {
	ret := VALUE(C.rb_get_argv())
	return ret
}

// RbLoadFile calls `rb_load_file` in C
//
// Original definition is following
//
//	void *rb_load_file(const char *file)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/ruby.h
func RbLoadFile(file string) unsafe.Pointer {
	char, clean := string2Char(file)
	defer clean()

	ret := unsafe.Pointer(C.rb_load_file(char))
	return ret
}

// RbLoadFileStr calls `rb_load_file_str` in C
//
// Original definition is following
//
//	void *rb_load_file_str(VALUE file)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/ruby.h
func RbLoadFileStr(file VALUE) unsafe.Pointer {
	ret := unsafe.Pointer(C.rb_load_file_str(C.VALUE(file)))
	return ret
}
