// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbFix2Short calls `rb_fix2short` in C
//
// Original definition is following
//
//	short rb_fix2short(VALUE num)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/short.h
func RbFix2Short(num VALUE) Short {
	ret := Short(C.rb_fix2short(C.VALUE(num)))
	return ret
}

// RbFix2Ushort calls `rb_fix2ushort` in C
//
// Original definition is following
//
//	unsigned short rb_fix2ushort(VALUE num)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/short.h
func RbFix2Ushort(num VALUE) Ushort {
	ret := Ushort(C.rb_fix2ushort(C.VALUE(num)))
	return ret
}

// RbNum2Ushort calls `rb_num2ushort` in C
//
// Original definition is following
//
//	unsigned short rb_num2ushort(VALUE num)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/short.h
func RbNum2Ushort(num VALUE) Ushort {
	ret := Ushort(C.rb_num2ushort(C.VALUE(num)))
	return ret
}
