// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbFloatNew calls `rb_float_new` in C
//
// Original definition is following
//
//	VALUE rb_float_new(double d)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/double.h
func RbFloatNew(d Double) VALUE {
	ret := VALUE(C.rb_float_new(C.double(d)))
	return ret
}

// RbFloatNewInHeap calls `rb_float_new_in_heap` in C
//
// Original definition is following
//
//	VALUE rb_float_new_in_heap(double d)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/double.h
func RbFloatNewInHeap(d Double) VALUE {
	ret := VALUE(C.rb_float_new_in_heap(C.double(d)))
	return ret
}
