// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbObjFreezeInline calls `rb_obj_freeze_inline` in C
//
// Original definition is following
//
//	void rb_obj_freeze_inline(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/fl_type.h
func RbObjFreezeInline(obj VALUE) {
	C.rb_obj_freeze_inline(C.VALUE(obj))
}

// RbObjInfect calls `RB_OBJ_INFECT` in C
//
// Original definition is following
//
//	RB_OBJ_INFECT(VALUE dst, VALUE src)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/fl_type.h
func RbObjInfect(dst VALUE, src VALUE) {
	C.RB_OBJ_INFECT(C.VALUE(dst), C.VALUE(src))
}

// RbObjInfectRaw calls `RB_OBJ_INFECT_RAW` in C
//
// Original definition is following
//
//	RB_OBJ_INFECT_RAW(VALUE dst, VALUE src)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/fl_type.h
func RbObjInfectRaw(dst VALUE, src VALUE) {
	C.RB_OBJ_INFECT_RAW(C.VALUE(dst), C.VALUE(src))
}

// RbObjTaint calls `RB_OBJ_TAINT` in C
//
// Original definition is following
//
//	RB_OBJ_TAINT(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/fl_type.h
func RbObjTaint(obj VALUE) {
	C.RB_OBJ_TAINT(C.VALUE(obj))
}

// RbObjTaintRaw calls `RB_OBJ_TAINT_RAW` in C
//
// Original definition is following
//
//	RB_OBJ_TAINT_RAW(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/fl_type.h
func RbObjTaintRaw(obj VALUE) {
	C.RB_OBJ_TAINT_RAW(C.VALUE(obj))
}
