// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

import (
	"unsafe"
)

// RbDataObjectZalloc calls `rb_data_object_zalloc` in C
//
// Original definition is following
//
//	VALUE rb_data_object_zalloc(VALUE klass, size_t size, RUBY_DATA_FUNC dmark, RUBY_DATA_FUNC dfree)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rdata.h
func RbDataObjectZalloc(klass VALUE, size SizeT, dmark unsafe.Pointer, dfree unsafe.Pointer) VALUE {
	ret := VALUE(C.rb_data_object_zalloc(C.VALUE(klass), C.size_t(size), toCPointer(dmark), toCPointer(dfree)))
	return ret
}

// RbDataObjectGet calls `rb_data_object_get` in C
//
// Original definition is following
//
//	rb_data_object_get(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rdata.h
func RbDataObjectGet(obj VALUE) unsafe.Pointer {
	ret := unsafe.Pointer(C.rb_data_object_get(C.VALUE(obj)))
	return ret
}

// RbDataObjectMake calls `rb_data_object_make` in C
//
// Original definition is following
//
//	rb_data_object_make(VALUE klass, RUBY_DATA_FUNC mark_func, RUBY_DATA_FUNC free_func, void **data/;"
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rdata.h
func RbDataObjectMake(klass VALUE, mark_func unsafe.Pointer, free_func unsafe.Pointer, datap unsafe.Pointer, size SizeT) VALUE {
	ret := VALUE(C.rb_data_object_make(C.VALUE(klass), toCPointer(mark_func), toCPointer(free_func), toCPointer(datap), C.size_t(size)))
	return ret
}
