// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

import (
	"unsafe"
)

// RbGlob calls `rb_glob` in C
//
// Original definition is following
//
//	void rb_glob(const char *pattern, void (*func)(const char *path, VALUE arg, void *enc), VALUE arg)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/glob.h
func RbGlob(pattern string, arg2 unsafe.Pointer, arg VALUE) {
	char, clean := string2Char(pattern)
	defer clean()

	C.rb_glob(char, toCPointer(arg2), C.VALUE(arg))
}
