// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbMatchextT is a type for passing `C.rb_matchext_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rmatch.h
type RbMatchextT C.rb_matchext_t

// RbMatchextStruct is a type for passing `C.rb_matchext_struct` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/core/rmatch.h
type RbMatchextStruct C.rb_matchext_struct
