// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbEncCoderangeClear calls `RB_ENC_CODERANGE_CLEAR` in C
//
// Original definition is following
//
//	RB_ENC_CODERANGE_CLEAR(VALUE obj)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/encoding/coderange.h
func RbEncCoderangeClear(obj VALUE) {
	C.RB_ENC_CODERANGE_CLEAR(C.VALUE(obj))
}

// RbEncCoderangeSet calls `RB_ENC_CODERANGE_SET` in C
//
// Original definition is following
//
//	RB_ENC_CODERANGE_SET(VALUE obj, enum ruby_coderange_type cr)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/encoding/coderange.h
func RbEncCoderangeSet(obj VALUE, cr RubyCoderangeType) {
	C.RB_ENC_CODERANGE_SET(C.VALUE(obj), C.ruby_coderange_type(cr))
}
