// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// Onigposition is a type for passing `C.OnigPosition` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/onigmo.h
type Onigposition C.OnigPosition

// RegexT is a type for passing `C.regex_t` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/onigmo.h
type RegexT C.regex_t

// ReRegisters is a type for passing `C.re_registers` in and out of package
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/onigmo.h
type ReRegisters C.re_registers
