// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by ruby_h_to_go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
*/
import "C"

// RbNum2CharInline calls `rb_num2char_inline` in C
//
// Original definition is following
//
//	rb_num2char_inline(VALUE x)
//
// ref. https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/char.h
func RbNum2CharInline(x VALUE) Char {
	ret := Char(C.rb_num2char_inline(C.VALUE(x)))
	return ret
}
