// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ruby

/*
#include "ruby.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// FdSet as declared in https://github.com/ruby/ruby/blob/master/include/ruby/_types/_fd_def.h
type FdSet struct {
	FdsBits        [32]int32
	ref89e67f53    *C.fd_set
	allocs89e67f53 interface{}
}

// FdMask type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/sys/types.h
type FdMask int32

// RUBYDATAFUNC type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/core/rdata.h
type RUBYDATAFUNC func(arg0 unsafe.Pointer)

// RbDataTypeT as declared in https://github.com/ruby/ruby/blob/master/include/ruby/core/rtypeddata.h
type RbDataTypeT struct {
	WrapStructName []byte
	Parent         []RbDataTypeT
	Data           unsafe.Pointer
	Flags          VALUE
	ref6b581591    *C.rb_data_type_t
	allocs6b581591 interface{}
}

// RbEventFlagT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/event.h
type RbEventFlagT uint32

// RbEventHookFuncT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/event.h
type RbEventHookFuncT func(evflag RbEventFlagT, data VALUE, self VALUE, mid ID, klass VALUE)

// RubyGlobFunc type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/glob.h
type RubyGlobFunc func(path string, arg VALUE, enc unsafe.Pointer) int32

// RbEnumeratorSizeFunc type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/intern/enumerator.h
type RbEnumeratorSizeFunc func(recv VALUE, argv VALUE, eobj VALUE) uint64

// RbArithmeticSequenceComponentsT as declared in https://github.com/ruby/ruby/blob/master/include/ruby/intern/enumerator.h
type RbArithmeticSequenceComponentsT struct {
	Begin          VALUE
	End            VALUE
	Step           VALUE
	ExcludeEnd     int32
	ref2cde3a4a    *C.rb_arithmetic_sequence_components_t
	allocs2cde3a4a interface{}
}

// RbHashUpdateFunc type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/intern/hash.h
type RbHashUpdateFunc func(newkey VALUE, oldkey VALUE, value VALUE) uint64

// RbFdsetT as declared in https://github.com/ruby/ruby/blob/master/include/ruby/select/largesize.h
type RbFdsetT struct {
	Maxfd          int32
	Fdset          []FdSet
	ref1f9fe814    *C.rb_fdset_t
	allocs1f9fe814 interface{}
}

// RbUnblockFunctionT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/intern/thread.h
type RbUnblockFunctionT func(arg0 unsafe.Pointer)

// RbBlockingFunctionT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/intern/thread.h
type RbBlockingFunctionT func(arg0 unsafe.Pointer) uint64

// RbAllocFuncT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/intern/vm.h
type RbAllocFuncT func(klass VALUE) VALUE

// RbBlockCallFunc type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/iterator.h
type RbBlockCallFunc func(yieldedArg VALUE, callbackArg VALUE, argc int32, argv []VALUE, blockarg VALUE) uint64

// RbBlockCallFuncT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/iterator.h
type RbBlockCallFuncT func(yieldedArg VALUE, callbackArg VALUE, argc int32, argv []VALUE, blockarg VALUE) uint64

// VALUE type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/value.h
type VALUE uint64

// ID type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/value.h
type ID uint64

// RbGvarGetterT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/variable.h
type RbGvarGetterT func(id ID, data []VALUE) uint64

// RbGvarSetterT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/variable.h
type RbGvarSetterT func(val VALUE, id ID, data []VALUE)

// RbGvarMarkerT type as declared in https://github.com/ruby/ruby/blob/master/include/ruby/internal/variable.h
type RbGvarMarkerT func(_var []VALUE)
