go-module:
  - changed-files:
      - any-glob-to-any-file: "ruby/**/*"

go_gem:
  - changed-files:
      - any-glob-to-any-file: "gem/**/*"

ruby_h_to_go:
  - changed-files:
      - any-glob-to-any-file: "_tools/ruby_h_to_go/**/*"

patch_for_go_gem:
  - changed-files:
      - any-glob-to-any-file: "_tools/patch_for_go_gem/**/*"
