# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rake/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("dummy.gemspec")

Rake::ExtensionTask.new("dummy", GEMSPEC) do |ext|
  ext.lib_dir = "lib/dummy"
end

desc "Check rbs"
task :rbs do
  sh "rbs collection install"
  sh "rbs validate"
  sh "steep check"
end

task default: %i[clobber compile spec]

task all: %i[clobber compile spec rubocop rbs]
