# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.ruby_opts = ["-r./test/test_helper"]
end

require "rake/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("example.gemspec.gemspec")

Rake::ExtensionTask.new("example", GEMSPEC) do |ext|
  ext.lib_dir = "lib/example"
end

desc "Check rbs"
task :rbs do
  sh "rbs collection install"
  sh "rbs validate"
  sh "steep check"
end

task default: %i[clobber compile test]

task all: %i[clobber compile test rbs]
